---
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /srv/dev-disk-by-uuid-8e8325f1-086c-464d-98e5-c92a714f9bca/appdata/Nextcloud/Config:/config
    ports:
      - ${PORT}:443
    restart: unless-stopped
    depends_on:
      - nextcloud_db
  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${Timezone}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /srv/dev-disk-by-uuid-8e8325f1-086c-464d-98e5-c92a714f9bca/appdata/Nextcloud/DB:/config
    restart: unless-stopped
